name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/bandit-check@1.6.2
      - uses: dciborow/action-pylint@0.0.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review    
          workdir: src
          level: warning
      - uses: jakebailey/pyright-action@v1.1.0
        with:
          project: pyproject.toml
      - uses: wemake-services/wemake-python-styleguide@0.15.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: src
          reporter: github-pr-review
          
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip
        python -m pip install pytest flit

        python -m flit install
        python -m pytest tests
          
