name: Pylint / Static Analysis
on:
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dciborow/action-pylint@0.0.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review    
          workdir: src
          level: warning
