name: wemake-python-styleguide

on:
  workflow_dispatch:

jobs:
  style-guide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.15.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: ${{ secrets.PACKAGE }}
          reporter: github-pr-review
